######################################################################
# Automatically generated by qmake (3.0) Fri Jul 22 23:12:43 2016
######################################################################

TEMPLATE = app
TARGET = Chaos
INCLUDEPATH += .

QT += widgets


# Input
HEADERS += Chaos.hpp Manager.hpp Elements.hpp
SOURCES += Chaos.cpp main.cpp Manager.cpp Elements.cpp
